[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1jkVzPlJe1indZnIGzG9S45F5O27tppCs?usp=sharing)

*Note: GitHub.com does not render everything when viewing these notbeook files, so click the "Open in Colab" button above to see everything as it's intended.*

# Python/Jupyter Review

This course assumes some "basic" familiarity with Python (cf. ["Learn the Basics" at LearnPython.org](https://www.learnpython.org/)).  We're not going to be doing what I'd call "hardcore" Python, and many "hard" things will be taken care of for you via utility routines so you'll often only have to "fill in the blanks" here and there.

Still, there's likely some need for review as well as to highlight important "tricks", and things you maybe haven't seen before. In particular, we'll be making use of the "science stack" (e.g., `numpy`, `matplotlib`,a little `pandas`) but not the "web stack" (e.g. not Flask or Django).  So, let's make a list of things you'll see in this course...


## Key Points about Python 

### It's superb for "messing around"
> "*Decades of programming in strongly-typed, declarative, pre- and post-allocation-based languages held me back from 'getting' this key fact about Python: It's extremely well-suited for **messing around**, ...and one of best playgrounds for messing around in is the Jupyter notebook environment.*" - S.H.

Everything is mutable, everything is overridable, everything is extendable. This is a blessing and a curse. For years I was preoccupied with the curse part, but you'll do well to remember the blessing side: you can do what you want (within limits)! 
<center><img src="https://d3qdvvkm3r2z1i.cloudfront.net/media/catalog/product/cache/1/thumbnail/85e4522595efc69f496374d01ef2bf13/d/o/dowhatiwant_newthumb-again.png" width="25%"></center>

It's not obvious that you'd want to write production code in Python: it *can* be fast, but it's not secure *at all*; for learning things and rapid prototyping though, it's awesome. 

### There's a Library/Package for Everything
I think this is another key to Python's success. Other languages have some of this (e.g. JavaScript & npm), but with Python there really is already some package that will do much of the heavy lifting for you if you want.

### Writing Fast Python is a 'Habit'

Speed matters for deep learning because we'll be dealing with *gajillions* of calculations, and a the difference between 10 microseconds vs. 10 milliseconds per operation will make the difference between you getting an answer to a homework problem in a few minutes vs. a few *days*.  (Again, this is a different mindset than, say, web programming in Python, where speed matters a bit but not nearly as much.)

<center><img src="https://i2.wp.com/comicsandmemes.com/wp-content/uploads/Famous-Movie-Qoutes-1986-Top-Gun-I-feel-the-need-for-speed.jpg?resize=768%2C401&ssl=1" width="40%"></center>

When you're first starting out, it's easy to accidentally write *really slow* code, particularly if you're coming from other programming languages. Learning to think in terms of "vectorized" operations and writing "one-liners" (e.g. "list comprehensions" which often are faster that multi-line implementations) can take some getting used to but eventually becomes a habit. So in what follows, we'll talk about few speedy ways of "prasing" things when writing Python code.

## Jupyter notebooks / Colab

You could write raw Python code as a text file and execute in the command-line (I used to do this), or use some IDE like PyCharm, but for this course we'll need access to **other people's computers** that give us access to GPUs (Graphics Processing Units) that we'll use for heavy number-crunching -- again, speed is key. 

Everything for this course is designed to be run on [Google Colab]() which is kind of a Google-Flavored version of the Jupyter environment. So, when I say "Jupyter notebooks", I mean like what the file I'm writing right now, regardless of whether it's hosted in an actual Jupyter environment (e.g. on Paperspace Gradient) or on Colab. Generally I'll assume Colab. 

(There are some special things you can do in regular-Jupyter that you can't do on Colab, and probably vice versa, but I'll try to minimize mention of those.) 

**TODO: come back and fill these in:**
* REPL
* Cell navigation
* Special moves: 
    * `!` shell commands 
    * `%` "magic" 
    * `?` documentation tricks 
* Colab vs. Jupyter
* Jupyter vs. IPython?



## Imports, Packages and Modules

**TODO:** Say something here.

"How do I make my own Python package?" is something we can cover later. 

## Key Packages For Us 
* **NumPy**: We're going to use the numerical package NumPy a *lot*, and when we compute things involving neural networks we'll use... 
* **PyTorch** for GPU-based computation. Our neural network calculations will typically exist "in" PyTorch.  PyTorch which has routines that are usually have the same name (though not always the same keyword arguments!) as the corresponding NumPy routines. 
* **FastAI** (also fast.ai or fastai) offers some powerful and convenient abstractions on top of PyTorch and some great integrations with other technologies, so we'll use it as well. 
* **MrsPuff:** And special just for this course, I've been creating a library called "[mrspuff](https://github.com/drscotthawley/mrspuff)" that will provide other useful functions for  things I want to teach you.
<center><img src="https://github.com/drscotthawley/mrspuff/raw/master/images/mrspuff_logo.png?raw=1" width="50%"></center>

Let's make sure we can install and import our key packages:

In [ ]:
# mrspuff already requires the other packages, so pip will grab them all
!pip install mrspuff | grep -v already

# Let's try to import our core packages
import numpy as np      # Everybody always abbreviates numpy as np
import torch            # The package for PyTorch is actually "torch" 
import fastai           # Usually we'll do "from fastai.xxxx import *"
import mrspuff as msp   # We may instead do "from mrspuff.xxxx import this, that, etc"

for p in [torch,fastai,msp]:  # and see what versions we have
    print(f'{p.__name__} {p.__version__}')

torch 1.7.1
fastai 2.3.0
mrspuff 0.0.23


### NumPy particulars

Most of the things on this page might be review for many people, but the numpy content is crucial.  The basic datatype for numpy is the *array*, which like a regular Python list but with many key improvements for (fast) numerical computations. 

#### Creating Arrays
There are lots of ways to create arrays, such as converting a list, or by using a special routines for special sets of numbers.  Here are some examples:

In [13]:
a= np.array([1,2,3,4,5,6])
print(f'a = {x}')
b = np.arange(6) # starts with 0, ends at 5
print(f'b = {y}')
print(f'c = {np.ones(6)}')
print(f'd = {np.zeros(7)}')
print(f"e = \n{np.eye(3)}")     # identity matrix "I" = "eye"
f = np.random.rand(4,5)         # 4 rows, 5 columns
print(f'f = \n{f}') 

a = [1 2 3 4 5 6]
b = [0 1 2 3 4 5]
c = [1. 1. 1. 1. 1. 1.]
d = [0. 0. 0. 0. 0. 0. 0.]
e = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
f = 
[[0.83180355 0.33936793 0.38292206 0.31851304 0.20155668]
 [0.75010399 0.63383556 0.93069906 0.85460757 0.03529984]
 [0.97388956 0.26762247 0.48944422 0.83834376 0.14665433]
 [0.23167385 0.99945914 0.35735899 0.50574351 0.00736664]]


#### Array Properties & Operations
* `shape` gives the number of rows and columns.  This is probably the most important property you will need to be checking and getting right! 

In [14]:
f.shape 

(4, 5)

* mathematical operations, which are eitherappended with a `.` or prepended with an `np.` (sometimes either way, sometimes only one way), e.g.:

In [49]:
print(f'f.mean() = {f.mean()}')
print(f'np.abs(f) = \n{np.abs(f)}')  # absolute value, note it's np.abs(f) not f.abs() ?
# the axis keyword can say along which axis (rows, columns..) the op is applied over
print(f'np.mean(f, axis=0) = {np.mean(f, axis=0)}')   
print(f'np.max(f,axis=1) = {np.max(f,axis=1)}')  # gets the max element 
print(f'np.argmax(f,axis=1) = {np.argmax(f,axis=1)}')  # gets the location of the max element 
print(f'f.sum(axis=1) = {f.sum(axis=1)}')
print(f'f.T = \n{f.T}')  # Transpose, reverses rows & columns
print(f'f.shape = {f.shape}, f.T.shape = {f.T.shape}')
# change the rows x column shape but # of elements must remain unchanged:
print(f'np.reshape(f, (2,10))  = \n{np.reshape(f, (2,10))}')  

f.mean() = 0.5048132876053942
np.abs(f) = 
[[0.83180355 0.33936793 0.38292206 0.31851304 0.20155668]
 [0.75010399 0.63383556 0.93069906 0.85460757 0.03529984]
 [0.97388956 0.26762247 0.48944422 0.83834376 0.14665433]
 [0.23167385 0.99945914 0.35735899 0.50574351 0.00736664]]
np.mean(f, axis=0) = [0.69686774 0.56007127 0.54010608 0.62930197 0.09771937]
np.max(f,axis=1) = [0.83180355 0.93069906 0.97388956 0.99945914]
np.argmax(f,axis=1) = [0 2 0 1]
f.sum(axis=1) = [2.07416327 3.20454603 2.71595433 2.10160212]
f.T = 
[[0.83180355 0.75010399 0.97388956 0.23167385]
 [0.33936793 0.63383556 0.26762247 0.99945914]
 [0.38292206 0.93069906 0.48944422 0.35735899]
 [0.31851304 0.85460757 0.83834376 0.50574351]
 [0.20155668 0.03529984 0.14665433 0.00736664]]
f.shape = (4, 5), f.T.shape = (5, 4)
np.reshape(f, (2,10))  = 
[[0.83180355 0.33936793 0.38292206 0.31851304 0.20155668 0.75010399
  0.63383556 0.93069906 0.85460757 0.03529984]
 [0.97388956 0.26762247 0.48944422 0.83834376 0.14665433 0.2316738

* vectorizing = speed. Treat arrays as single objects, then operations can be applied to all elements at once very quickly. For example:

In [45]:
g = np.random.rand(1000,10000)   # define lots of numbers

In [46]:
%%timeit                # handy trick for timing code
a = g/2  # treat f like a sigle thing

100 loops, best of 5: 15 ms per loop


In [47]:
%%timeit
a = np.empty(g.shape)
for i in range(g.shape[0]):
    for j in range(g.shape[1]):
        a = g[i,j]/2      # try to operate on each element in succession

1 loop, best of 5: 5.31 s per loop


* **Slicing** is super-important. It's how we specify subsets of arrays. Typicaly this is done with numbers specifying array indices to slice at, the colon `:` to denote "wildcard" values, and commas to separate axes. Note that tegative indices are counted backwards from the end of the arrray. Here are some examples:



In [63]:
a = np.arange(12).reshape((3,4))
print(f'a = \n{a}')
print(f'a[:,2] = {a[:,2]}')  # the second column; but not it will become a 1.array
print(f'a[:,2,np.newaxis] = \n{a[:,2,np.newaxis]}') # newaxis can create an axis if one was lost
print(f'a[1:,:-1] = {a[1:,-1]}') # all rows after the first one, and the last column


a = 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[:,2] = [ 2  6 10]
a[:,2,np.newaxis] = 
[[ 2]
 [ 6]
 [10]]
a[1:,:-1] = [ 7 11]


sliced parts of arrays are called "views": they are are not re-generated as new arrays, they are just "views" of the old array.  If you want to add or operate on slices of arrays, they must have the same shape.

* **Broadcasting** is the exception to arrays being the same shape.  It lets you combine a large array with a smaller one in certain ways:

In [66]:
print(f"a + 5 = \n{a+5}") # We can broadcast scalars
print(f"a + np.ones(2) = {a+np.ones(2)}")

a + 5 = 
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


ValueError: ignored

Ohhh woopsie.  See, the shapes didn't match. How about if we match the last dimension (4)...?

In [69]:
print(f"a + np.ones(3) = \n{a+np.ones(4)}")

a + np.ones(3) = 
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


Good. See, in order for arrays to be in joint operations together, the *last dimension* (in this cas 4) has to be the same.  What NumPy does is it creates a "broadcast view" of the smaller array to where it's the same size as the big array, i.e. it creates, in the example above, a 3x4 array of ones out of the 4-element array of ones. Then it adds these two "big arrays" together. 

* `random` and seed

## Functions & Methods

TODO: say something general here. 

### lambda is just a function with no name
I'm not going to make you write "lambda" functions, but if you see one don't worry, it's the same as an unnamed function (e.g. there's no "def __name__()"). And because everything is mutable, you can *give it* name. So the following 3 snippets do the same thing:

In [ ]:
def a(x): return x+5
print("a =",a(4))

b = lambda x: x+5 
print(f"b = {b(4)}")

a = 9
b = 9


...Oh yea, see in that last line I used a "f-string." They've been a feature since Python 3.5. We'll use them a lot because I think they're great. But if you try to use an older Python interpreter (e.g. Python 2.7), you'll get a syntax error.  Actually everything we'll be doing will assume at least Python 3.6. Let's see what version we're running:

In [ ]:
import sys
print(f"Python version is {sys.version}")

Python version is 3.7.10 (default, Feb 20 2021, 21:17:23) 
[GCC 7.5.0]


### Generators are not that bad
A [generator](https://www.learnpython.org/en/Generators) is just a function with the word "yield" in it (which functions kind of like "return") and they can be used as iterators (e.g. for for loops & list comprehensions).  Here's a generator. 

In [ ]:
def gen(z, step=1):
    count = 0
    for i in range(z):       # this is a standard for loop, see below
        count += step
        yield(count)

print([x for x in gen(10)])  # this is a list comprehension, see below
print([x for x in gen(10,step=-2)])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[-2, -4, -6, -8, -10, -12, -14, -16, -18, -20]


They are often use to supply the next batch of data to something, like we'll do when training our neural networks.  But this will mostly be done for us by our library routines; I don't think you'll need to write your own generators. 


## Classes 
and namespaces


 

## Data types


### Lists 

 

### Dictionaries 
[Dictionaries](https://www.learnpython.org/en/Dictionaries) are great, especially as fast "[hashes](https://en.wikipedia.org/wiki/Hash_function)", i.e. as fast look-up-functions between two sets of data.  The Pandas data science library is largely based on dictionaries. 




## Loops
Different ways of writing loops can be faster or slower than others, and it depends on the application and the number of iterations. Generally,
* Try avoid loops for simple things, instead prefer vectorized numpy operations, e.g. use `.mean()` on a NumPy array instead of  looping over all elements and keeping a running sum and then dividing by the number of iterations.

In [ ]:
arr = np.random.rand(99999999)  # generate lots o' numbers

In [ ]:
%%timeit
arr.mean()

10 loops, best of 5: 69.4 ms per loop


In [ ]:
%%timeit 
sum, n = 0, len(arr)
for i in range(n):
    sum += arr[i]
mean = sum/n

1 loop, best of 5: 28 s per loop


...yeah.  Which one is faster?


* When we write loops, there are 3 main ways we do it. Letting y denone some iterator such as `range(n)` or a list, then these 3 ways are:
   1. standard loops: `for x in y: _somthing_involving_x` (and yes, loops can be one-liners or they can span multiple lines)
   2. list comprehensions: `[_somthing_involving_x for x in y]`
   3. (more advanced) `map` operations: `_some_list_ = list(map(func, y))`

Handy loop iterators:
* range 
* enumerate() & zip() 

If you're looping in order to build up a bunch of data or do a bunch of single operations, then [List comprehensions](https://www.learnpython.org/en/List_Comprehensions) usually preferable.  

Let's do a comparison:

## Plotting:
* matplotlib 
* Others

## Pandas stuff:
