^ [CLICK HERE TO OPEN THIS NOTEBOOK IN COLAB](https://colab.research.google.com/github/drscotthawley/DLAIE/blob/main/Assignments/A2_Sample_NN.ipynb), then do **"File > Save a Copy In Drive" and edit it on your own.** 

...And then for grading, set your Colab notebook to "Shareable", and post the "Sharing Link" into the Google Form to which Dr. Hawley will email a link to the class.

In [ ]:
!pip install numpy torch -Uqq

In [ ]:
import numpy as np
import torch 
import torch.nn as nn
import torch.nn.functional as F

Create a PyTorch model of the Module class, call it MyNet, which will have two hidden layers of neurons.  Fill in your code on the lines between the `>>>>START` and `END<<<<` markings:


In [ ]:
# GRADED EXERCISE 2.1
class MyNet(nn.Module):    # leave the class definition & parameters alone
    def __init__(self, 
        in_dim,      # dimensions of input (number columns for input)
        hidden_dim1, # number of neurons in the 1st hidden layer
        hidden_dim2, # number of neurons in the 2nd hidden layer
        out_dim): # dimensions of output
        super().__init__()  

        # On the following lines, define 3 PyTorch nn.Linear layers to connect...
        #   1. the input to the first hidden layer
        #   2. the first hidden layer to the second hidden layer
        #   3. the second hidden layer with the output
        # You may name these whatever you like, but start them with "self."
        #>>>>START your code block below 
        


        #<<<<END of your code block above

    # In the forward method: pass the 'x' through the following successive steps
    #  1. run 'x' through first layer you defined above
    #  2. apply a "torch.tanh" activation to the result of step 1  (used to be F.tanh but they changed it!s)
    #  3. run the result of step 2 through the second linear layer you defined
    #  4. apply a "F.relu" activation to that
    #  5. run that result through the third layer with no activation, and assign that to x
    #  ...then we'll return x of that as your model's output
    def forward(self, x): 
        #>>>>START your code block below          


        #<<<<END of your code block above
        return x

We're just going to do random initialization, and random data. 

In [ ]:
torch.manual_seed(0)   # initialize the random number generator

batch_size, in_dim, out_dim = 2, 3, 1 
x = torch.rand((batch_size, in_dim))
x

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

Now let's define a network

In [ ]:
hd1, hd2 = 20, 20    # hidden layer dimensions
mynet = MyNet(in_dim, hd1, hd2, out_dim)

And run our data through the model to obtain a set of predictions, "preds"

In [ ]:
preds = mynet.forward(x)
preds

tensor([[0.1995],
        [0.1767]], grad_fn=<AddmmBackward>)

We got a number of predictions equal to `batch_size`.  The extra `grad_fn=` part we're not going to use in this assignment--it's needed for training the network but GitHub won't let us do that easily.

To "detach" the gradient info, we just use the `.detach()` method:

In [ ]:
preds.detach()

tensor([[0.1995],
        [0.1767]])

And then if we want to do something with it using NumPy instead of PyTorch, there's a `.numpy()` method:

In [ ]:
p = preds.detach().numpy(); p

array([[0.19950144],
       [0.1766648 ]], dtype=float32)

^ the `dtype=float32` is just telling us that these numbers are 32-bit floating point numbers.  You don't need to do anything with that information.  If we use `print()` then we won't see that:

In [ ]:
print(p)

[[0.19950144]
 [0.1766648 ]]


Now let's do some tests

In [ ]:
x2 = torch.tensor([[1,2,3],[4,5,6]])
print("x2 =\n",x2)
x2 = x2.float() # actually let's make it floats instead of ints
print("x2 =\n",x2)
batch_size, in_dim = x2.shape[0], x2.shape[1]; 
print(f"batch_size = {batch_size}, in_dim = {in_dim}")

torch.manual_seed(0)
mynet2 = MyNet( in_dim, 10, 10, 1 )

x2 =
 tensor([[1, 2, 3],
        [4, 5, 6]])
x2 =
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
batch_size = 2, in_dim = 3


And let's run it through 

In [ ]:
p2 = mynet2.forward(x2).detach().numpy()
print(p2)

[[-0.13569488]
 [-0.18428665]]


#### Assertion Check:
This will be a way of testing whether your answers are close enough to those obtained by the instructor. If no output appears, it means you passed!

In [ ]:
tol = 1e-6   # some tolerable level of precision
target = np.array([[-0.13569488], [-0.18428665]])  # my answer (to some precision based on cut & paste!)
assert np.abs(p2 - target).sum() < tol, "Nope the difference is too great."

In [ ]:
# Let me prepare some code to make this more convenient 
def check_preds(net, x, target, tol=1e-6):
    preds = net.forward(x).detach().numpy()
    assert np.abs(preds - target).sum() < tol, "Nope the difference is too great."
    print("Passed the test!")

In [ ]:
torch.manual_seed(0)
net = MyNet(x2.shape[1], 10,10, target.shape[1])
check_preds(net, x2, target)

Passed the test!


In [ ]:
torch.manual_seed(0)
x3 = torch.rand((3,4))   # a batch of 3 input vectors with 4 elements each
net = MyNet(x3.shape[1], 30,30, 1)
target = np.array([[-0.3079027 ],[-0.34663504],[-0.30993503]]) # what I got
check_preds(net, x3, target)

Passed the test!


# That's it for now
We could go on and do more tests, and graphs, and samples of training.  Let's just see if we have this much working before moving on!